#! /bin/bash
check(){
	run=$(mpc status | wc -l)
	if [ $run == 3 ]; then
		echo "Not running"
		exit
	if [ $run -lt 0 ]; then
		echo "Is running"
		exit
	fi
	fi
if [ ! -f "~/conky.pid" ]; then
pid_orig=`cat ~/conky.pid`
fi

pid_new=`pgrep -a conky | grep music | awk '{print $1}'`

if [ "$pid_new" != "$pid_org" ]; then
kill $pid_new
fi
}

run(){
conky -c ~/.config/conky/modules/music &
 conk_var=`pgrep -a conky | grep music | awk '{print $1}'`
touch ~/conky.pid
echo $conk_var > conky.pid
#pidof -o %PPID -x $0 >/dev/null && echo "ERROR: Script $0 already running" && exit 1
}

mpc(){
echo "test"
}

main(){
check
run
echo "Notnig to see"
}

main

