#!/bin/bash

check(){
conk_pid=$(pgrep -a conky | grep music | awk '{print $1}')
if [ -f "~/conky.pid" ]; then
pid_orig=`cat ~/conky.pid`
else
	return 0
fi

pid_new=`pgrep -a conky | grep music | awk '{print $1}'`

if [ "$pid_new" != "$pid_org" ]; then
kill $pid_new
fi
}

run(){
conky -c ~/.config/conky/modules/music &
 conk_var=`pgrep -a conky | grep music | awk '{print $1}'`
touch ~/conky.pid
echo $conk_var > conky.pid
#pidof -o %PPID -x $0 >/dev/null && echo "ERROR: Script $0 already running" && exit 1
}

mpd(){
# Check if both mpd and ncmpcpp are active
while true; do
if pgrep -x "mpd" > /dev/null && pgrep -x "ncmpcpp" > /dev/null && mpc | grep -q "playing"; then
	    # Run the Conky module (replace <path_to_your_conkyrc> with the actual path to your conky configuration file)
	        conky -c  $HOME/.config/conky/modules/music &
		exit
	else
		    echo "mpd or ncmpcpp is not active"
		    sleep 1s
fi
done
}

main(){
check
mpd
run
}

main

