#!/bin/sh
# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# URLs will be directly handed to the browser.
# Anything else, it search it.
YTS='st -e youtube-viewer'
YT_search=${youtube-viewer}

pgrep -x dmenu && exit

choice=$(echo ":" | dmenu -i -p  "Search Youtube:" -fn 'NotMonoRegular:bold:pixelsize=18') || exit 1

if [ "$choice" = "🦆"  ]; then
  $choice | $YTS
fi
