" ~/.vimrc - Optimized for Programming + Readability (2026)

set nocompatible
filetype plugin indent on
syntax enable

" ── Core settings ───────────────────────────────────────────────────
set encoding=utf-8
set number relativenumber
set signcolumn=auto
set clipboard=unnamedplus
set mouse=a
set visualbell t_vb=
set splitbelow splitright
set ignorecase smartcase
set nohlsearch
set wildmode=longest:full,full
set completeopt=menuone,noinsert,noselect
set laststatus=2
set background=dark

let mapleader = ","

" Disable auto-comment
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Trim trailing whitespace
autocmd BufWritePre * %s/\s\+$//e

" ── Improved Relative Numbers ───────────────────────────────────────
set numberwidth=6

augroup RelativeNumberToggle
	    autocmd!
	        autocmd InsertEnter * set norelativenumber
		    autocmd InsertLeave * set relativenumber
augroup END

nnoremap <leader>r :set relativenumber!<CR>

" ── Sign Column Styling ─────────────────────────────────────────────
highlight SignColumn ctermbg=0 guibg=#000000

" Visible error/warning signs
highlight ALEErrorSign   cterm=bold ctermfg=9  guifg=#ff0000 gui=bold
highlight ALEWarningSign cterm=bold ctermfg=11 guifg=#ffff00 gui=bold
highlight CocErrorSign   cterm=bold ctermfg=9  guifg=#ff0000 gui=bold
highlight CocWarningSign cterm=bold ctermfg=11 guifg=#ffff00 gui=bold

" ── Enhanced Crosshair (more visible) ───────────────────────────────
set cursorline
set cursorcolumn

augroup CursorCrosshair
	    autocmd!
	        autocmd WinEnter * set cursorline cursorcolumn
		    autocmd WinLeave * set nocursorline nocursorcolumn
augroup END

highlight CursorLine   cterm=bold ctermbg=236 guibg=#303030 gui=bold
highlight CursorColumn cterm=bold ctermbg=237 guibg=#3a3a3a gui=bold

highlight CursorLineNr cterm=bold ctermfg=11 guifg=#ffff00 gui=bold

" ── Ruler ───────────────────────────────────────────────────────────
set ruler
set rulerformat=%l,%c%V

" ── Plugin Manager ──────────────────────────────────────────────────
if empty(glob('~/.vim/autoload/plug.vim'))
	    echo "Downloading vim-plug..."
	        silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
			    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Core
Plug 'preservim/nerdtree'
Plug 'junegunn/goyo.vim'
Plug 'chrisbra/Colorizer'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'vimwiki/vimwiki'

" Programming
Plug 'w0rp/ale'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/tagbar'

" Intelligent Autocompletion
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

" ── Powerline ───────────────────────────────────────────────────────
set rtp+=/usr/share/powerline/bindings/vim

" ── Plugin Settings & Mappings ──────────────────────────────────────

" NERDTree
let NERDTreeShowLineNumbers=1
autocmd FileType nerdtree setlocal relativenumber
map <leader>n :NERDTreeToggle<CR>

" Goyo
map <leader>f :Goyo<CR>

" Colorizer
let g:colorizer_auto_filetype = '*'
let g:colorizer_skip_comments = 1

" Tagbar
nmap <leader>t :TagbarToggle<CR>

" FZF
nnoremap <leader>p :Files<CR>
nnoremap <leader>g :Rg<CR>

" ALE
let g:ale_sign_error = '✘'
let g:ale_sign_warning = '⚠'

" CoC Settings
let g:coc_global_extensions = [
	    \ 'coc-json',
	        \ 'coc-clangd',
		    \ 'coc-pyright',
		        \ 'coc-tsserver',
			    \ 'coc-html',
			        \ 'coc-css'
    \ ]

inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
            \ CheckBackspace() ? "\<Tab>" :
	          \ coc#refresh()

inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
	  let col = col('.') - 1
	    return !col || getline('.')[col - 1]  =~# '\s'
endfunction

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nnoremap <silent> K :call CocActionAsync('doHover')<CR>

" Spell check
map <leader>o :setlocal spell! spelllang=en_us<CR>

" Split navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Quick save/quit
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

" End of config
