#! /bin/bash
check(){
if [ ! -f "~/conky.pid" ]; then
pid_orig=`cat ~/conky.pid`
fi

pid_new=`pgrep -a conky | grep music | awk '{print $1}'`

if [ "$pid_new" != "$pid_org" ]; then
kill $pid_new
fi
}

run(){
conky -c ~/.config/conky/modules/music &
 conk_var=`pgrep -a conky | grep music | awk '{print $1}'`
touch ~/conky.pid
echo $conk_var > conky.pid
#pidof -o %PPID -x $0 >/dev/null && echo "ERROR: Script $0 already running" && exit 1
}

mpc(){
dunstify -a "mpc-notifier" -u low -t 2000 "$1"


	    # Main loop to check for changes in mpc status
while true; do
current_status=$(mpc status | head -n 1)

if [ "$current_status" != "$previous_status" ]; then
send_notification "MPD: $current_status"
previous_status="$current_status"
fi

sleep 1
done
}

main(){
check
run
#mpc
}

main

