#!/bin/bash

# Function to send notification using Dunst
send_notification() {
	    dunstify -a "mpc-notifier" -u normal -t 5000 "$1"
    }

    # Main loop to check for changes in mpc status
previous_status=""
while true; do

current_status=$(mpc status | head -n 1)
current_state=$(mpc status | head -n 2 | grep -iE 'playing|paused' | cut -c 1-9 | tr -d '[]')
if [ "$current_status" != "$previous_status" ]; then
send_notification "Now Playing: $current_status"
conky-toggle
fi
mpc idle player
previous_status="$current_status"
done

