#! /bin/sh

go(){
oPID="$$"
espeak "Time started. 5 minutes remaining."
aucat -i ~/.config/sounds/chime.wav
echo $oPID > .timer.pid
sleep 300
espeak "Timer ended."
aucat -i ~/.config/sounds/buzzer.wav
return 0
}

check(){
if [ -f .timer.pid ] ; then
chk=`cat .timer.pid`
#nPID="$$"
if [ $chk != '' ] ; then
		espeak "Error: timer already running".
	kill $chk 2>/dev/null
	exit
else
		espeak "not found!"
fi
fi
return 0
}

clean(){
if [ -f .timer.pid ] ; then
#		espeak "PID file found deleting!"
		rm .timer.pid
#		espeak "PID file not found."
fi
return 0
}

main(){
check 
go
clean
exit
}

main
